<?php
echo ('<div class="container">');
echo ('<font face="arial" size="2" color="#888888">');
echo ('� 2019, All Rights Reserved. IKEF is a not-for-profit Fan organization devoted to portraying the Klingon way of life through Live action gaming/Role playing');
echo ('<br>');
echo ('No copyright infringement is intended for use of Star Trek Terms and expressions. Star Trek is a registered trademark of Paramount Pictures / Viacom.');
echo ('<br>');
echo ('No Copyright Infringement is intended for use of artwork, terms, or anything pertaining to Star Trek, ST: TNG, DS9, Voyager, Enterprise or other forms');
echo ('<br>');
echo ('of the franchise. If a more specific and complete copyright disclaimer is needed, the webmaster/web author will comply with a reasonable request directly from Paramount Pictures /CBS/ Viacom.');
echo ('</font>');
echo ('</div>');
echo ('<div id="zbl-NavFooter">');
echo ('<!-- do not add styling to this div -->');
echo ('<div>');
echo ('<div class="container-links">');
echo ('<table id="table-links">');
echo ('<tr>');
echo ('<td>');
echo ('<a href="http://www.ikefklingons.com/index.html" class="selected" title="Home">Home</a>');
echo ('</td>');
echo ('<td>');
echo ('<a href="http://www.ikefklingons.com/sectors/sectors.html" title="Sectors">Sectors</a>');
echo ('</td>');
echo ('<td>');
echo ('<a href="http://www.ikefklingons.com/departments/departments.html" title="Departments">Departments</a>');
echo ('</td>');
echo ('<td>');
echo ('<a href="http://www.ikefklingons.com/highcouncil/highcouncil.html" title="High Council">IKEF High Council</a>');
echo ('</td>');
echo ('<td>');
echo ('<a href="http://www.ikefklingons.com/marines/marines.html" title="IKEF Marines">IKEF Marines</a>');
echo ('</td>');
echo ('<td>');
echo ('<a href="http://www.ikefklingons.com/communications/" target="_comm" title="IKEF Forum">IKEF Forum</a>');
echo ('</td>');
echo ('<td>');
echo ('<a href="https://form.jotform.com/91735355836163" title="Chain of Command/Operations">Join IKEF</a>');
echo ('</td>');
echo ('</tr>');
echo ('</table>');
echo ('</div>');
echo ('</div>');
echo ('</div>');
echo ('</font>');
?>